# Optional Lab: Python, NumPy and Vectorization
이 과정에서 사용되는 일부 과학 컴퓨팅에 대한 간략한 소개입니다. 특히 NumPy 과학 컴퓨팅 패키지와 Python과의 사용 방법.


# Outline
- [&nbsp;&nbsp;1.1 Goals](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 Useful References](#toc_40015_1.2)
- [2 Python and NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 Vectors](#toc_40015_3)
- [&nbsp;&nbsp;3.1 Abstract](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy Arrays](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 Vector Creation](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 Operations on Vectors](#toc_40015_3.4)
- [4 Matrices](#toc_40015_4)
- [&nbsp;&nbsp;4.1 Abstract](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy Arrays](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 Matrix Creation](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 Operations on Matrices](#toc_40015_4.4)

In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 Goals
이 실습에서는 다음을 수행합니다.
- 강좌 1에서 사용된 NumPy와 Python의 특징들을 검토합니다.

<a name="toc_40015_1.2"></a>
## 1.2 Useful References
- NumPy Documentation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
# 2 Python and NumPy <a name='Python and NumPy'></a>
Python은 이번 강좌에서 사용할 프로그래밍 언어입니다. 여기에는 일련의 숫자 데이터 유형과 산술 연산이 있습니다. NumPy는 Python의 기본 기능을 확장하여 더 많은 숫자 유형, 벡터, 행렬 및 많은 행렬 함수를 포함하는 보다 풍부한 데이터 세트를 추가하는 라이브러리입니다. NumPy와 Python은 매우 원활하게 함께 작동합니다. Python 산술 연산자는 NumPy 데이터 유형에서 작동하며, 많은 NumPy 함수는 Python 데이터 유형을 허용합니다.

<a name="toc_40015_3"></a>
# 3 Vectors
<a name="toc_40015_3.1"></a>
## 3.1 Abstract
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >
이 과정에서 사용하게 될 벡터는 순서가 지정된 숫자 배열입니다. 표기법에서 벡터는 $\mathbf{x}$와 같이 굵은 소문자로 표시됩니다. 벡터의 요소는 모두 동일한 유형입니다. 예를 들어 벡터에는 문자와 숫자가 모두 포함되지 않습니다. 수학자들은 *순위(rank)*를 선호하지만 배열의 요소 수는 종종 *차원(dimension)*이라고 합니다. 표시된 벡터의 차원은 $n$입니다. 벡터의 요소는 인덱스로 참조될 수 있습니다. 수학 설정에서 인덱스는 일반적으로 1부터 n까지 실행됩니다. 컴퓨터 과학 및 이러한 실습에서 인덱싱은 일반적으로 0에서 n-1까지 실행됩니다. 표기법에서 벡터의 요소는 개별적으로 참조될 때 아래 첨자의 인덱스를 나타냅니다. 예를 들어 $\mathbf{x}$ 벡터의 $0^{th}$ 요소는 $x_0$입니다. 이 경우 x는 굵게 표시되지 않습니다.

<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

NumPy의 기본 데이터 구조는 동일한 유형(`dtype`)의 요소를 포함하는 색인 가능한, n-차원 *배열(array)*입니다. '차원(dimension)'이라는 용어가 너무 많이 사용되었음을 바로 알 수 있습니다. 위에서는 벡터의 요소 수였지만, 여기서 차원은 배열의 인덱스 수를 나타냅니다. 1-차원 또는 1-D 배열에는 하나의 인덱스가 있습니다. 코스 1에서는 벡터를 NumPy 1-차원 배열로 표현하겠습니다.

  - 1-D 배열, shape (n,): [0]부터 [n-1]까지 인덱스가 있는 n개 요소

<a name="toc_40015_3.3"></a>
## 3.3 Vector Creation


NumPy의 데이터 생성 루틴에는 일반적으로 객체의 모양인 첫 번째 매개변수가 있습니다. 이는 1-D 결과에 대한 단일 값이거나, 결과의 모양(shape)을 지정하는 튜플 (n,m,...)일 수 있습니다. 다음은 이러한 루틴을 사용하여 벡터를 생성하는 예입니다.

In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.50624638 0.58114379 0.83037724 0.32020282], a shape = (4,), a data type = float64


일부 데이터 생성 루틴은 모양 튜플(shape tuple)을 사용하지 않습니다.:

In [3]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.25990871 0.49866054 0.86927206 0.15077599], a shape = (4,), a data type = float64


값을 수동으로 지정할 수도 있습니다.

In [4]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


이것들은 모두 4개의 요소를 가진 1-D 벡터 'a'를 생성했습니다. `a.shape`는 크기를 반환합니다. 여기서는 4개의 요소가 있는 1-D 배열을 나타내는 a.shape = `(4,)`를 볼 수 있습니다.

<a name="toc_40015_3.4"></a>
## 3.4 Operations on Vectors
벡터를 사용한 몇 가지 연산을 살펴보겠습니다.
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Indexing
벡터의 요소는 인덱싱 및 슬라이싱을 통해 액세스할 수 있습니다. NumPy는 매우 완벽한 인덱싱 및 슬라이싱 기능 세트를 제공합니다. 여기서는 강좌에 필요한 기본 사항만 살펴보겠습니다. 자세한 내용은 [슬라이싱 및 인덱싱](https://NumPy.org/doc/stable/reference/arrays.indexing.html)을 참조하세요.
**인덱싱(Indexing)** 은 배열 내의 위치를 기준으로 배열의 *요소*를 참조하는 것을 의미합니다.
**슬라이싱(Slicing)** 은 인덱스를 기반으로 배열에서 요소의 *하위 집합*을 가져오는 것을 의미합니다.
NumPy는 0부터 인덱싱을 시작하므로 벡터 $\mathbf{a}$의 세 번째 요소는 `a[2]`입니다.

In [6]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 Slicing
슬라이싱(Slicing)은 세 가지 값 세트(`start:stop:step`)를 사용하여 인덱스 배열을 생성합니다. 값의 하위 집합도 유효합니다. 그 사용법은 다음 예를 통해 가장 잘 설명됩니다.

In [7]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Single vector operations
단일 벡터에 대한 연산과 관련된 유용한 연산이 많이 있습니다.

In [8]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector element-wise operations
NumPy 산술, 논리 및 비교 연산의 대부분은 벡터에도 적용됩니다. 이러한 연산자는 요소별로 작동합니다. 예를 들어
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [9]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


물론 이것이 올바르게 작동하려면 벡터의 크기가 동일해야 합니다.

In [10]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations
벡터는 스칼라 값으로 '크기 조정'될 수 있습니다. 스칼라 값은 단지 숫자일 뿐입니다. 스칼라는 벡터의 모든 요소를 곱합니다.

In [11]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 Vector Vector dot product
내적(dot product)은 선형 대수학(Linear Algebra)과 NumPy의 핵심입니다. 이는 이 과정에서 광범위하게 사용되는 작업이므로 잘 이해해야 합니다. 내적은 아래와 같습니다.

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800>

내적은 두 벡터의 값을 요소별로 곱한 다음 결과를 합산합니다.
벡터 내적은 두 벡터의 차원이 동일해야 합니다.

아래 내적의 자체 버전을 구현해 보겠습니다.

**for 루프를 사용하여** 두 벡터의 내적을 반환하는 함수를 구현합니다. 주어진 입력 $a$ 및 $b$를 반환하는 함수:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
`a` 와 `b`가 모두 같은 모양이라고 가정합니다.


In [12]:
def my_dot(a, b):
    """
   Compute the dot product of two vectors

    Args:
      a (ndarray (n,)):  input vector
      b (ndarray (n,)):  input vector with same dimension as a

    Returns:
      x (scalar):
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [13]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


내적은 스칼라 값을 반환할 것으로 예상됩니다.

`np.dot`을 사용하여 동일한 작업을 시도해 보겠습니다.


In [ ]:
# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ")
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


위에서 1-D 결과가 우리의 구현과 일치한다는 것을 알 수 있습니다.

<a name="toc_40015_3.4.7"></a>
### 3.4.7 The Need for Speed: vector vs for loop
우리는 속도 메모리 효율성을 향상시키기 위해 NumPy 라이브러리를 활용했습니다. 다음을 보여드리겠습니다.

In [ ]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 29.9268 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2137.4848 ms 


따라서 이 예에서는 벡터화를 통해 속도가 크게 향상됩니다. 이는 NumPy가 기본 하드웨어에서 사용 가능한 데이터 병렬성을 더 잘 활용하기 때문입니다. GPU와 최신 CPU는 SIMD(Single Instruction, Multiple Data) 파이프라인을 구현하여 여러 작업을 병렬로 실행할 수 있습니다. 이는 데이터 세트가 매우 큰 경우가 많은 기계 학습에서 매우 중요합니다.

<a name="toc_12345_3.4.8"></a>
### 3.4.8 Vector Vector operations in Course 1
벡터-벡터 연산은 강좌 1에서 자주 등장합니다. 그 이유는 다음과 같습니다.
- 앞으로 예제는 차원 (m,n)의 `X_train` 배열에 저장됩니다. 이에 대해서는 문맥을 통해 더 자세히 설명하겠지만 여기서는 이것이 2차원 배열 또는 행렬이라는 점에 유의하는 것이 중요합니다(행렬에 대한 다음 섹션 참조).
- `w`는 (n,) 모양의 1차원 벡터가 됩니다.
- 예제를 반복하면서 작업을 수행하고 X를 인덱싱하여 개별적으로 작업할 각 예제를 추출합니다. 예:`X[i]`
- `X[i]`는 1차원 벡터인 (n,) 형태의 값을 반환합니다. 결과적으로 `X[i]`와 관련된 연산은 벡터-벡터인 경우가 많습니다.

설명이 다소 길지만 벡터 연산을 수행할 때 피연산자의 모양을 정렬하고 이해하는 것이 중요합니다.


In [ ]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 Matrices


<a name="toc_40015_4.1"></a>
## 4.1 Abstract
 행렬은 2차원 배열입니다. 행렬의 요소는 모두 동일한 유형입니다. 표기법에서 행렬은 $\mathbf{X}$와 같이 대문자, 굵은 문자로 표시됩니다. 이 실습과 다른 실습에서 `m`은 행 수이고 `n`은 열 수인 경우가 많습니다. 행렬의 요소는 2차원 인덱스로 참조될 수 있습니다. 수학 설정에서 색인의 숫자는 일반적으로 1부터 n까지입니다. 컴퓨터 과학 및 이러한 실습에서 인덱싱은 0 에서 n-1까지 실행됩니다.
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Generic Matrix Notation, 1st index is row, 2nd is column </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## 4.2 NumPy Arrays

NumPy의 기본 데이터 구조는 동일한 유형(`dtype`)의 요소를 포함하는 색인 가능한 n차원 *배열*입니다. 이에 대해서는 앞서 설명했습니다. 행렬은 2차원(2-D) 인덱스 [m,n]을 갖습니다.

코스 1에서는 훈련 데이터를 저장하기 위해 2차원 행렬이 사용됩니다. 훈련 데이터는 (m,n) 배열을 생성하는 $n$ 특징의 $m$ 예입니다. 과정 1에서는 행렬에 대해 직접 연산을 수행하지 않지만 일반적으로 예제를 벡터로 추출하여 연산합니다. 아래에서 검토할 내용은 다음과 같습니다.
- 데이터 생성
- 슬라이싱 및 인덱싱


<a name="toc_40015_4.3"></a>
## 4.3 Matrix Creation
1차원 벡터를 생성한 동일한 함수가 2차원 또는 n차원 배열을 생성합니다. 여기 몇 가지 예가 있어요


아래에서는 2차원 결과를 얻기 위해 모양 튜플이 제공됩니다. NumPy가 대괄호를 사용하여 각 차원을 표시하는 방법에 주목하세요. NumPy보다 더 중요한 점은 인쇄할 때 한 줄에 한 행씩 인쇄한다는 것입니다.

In [ ]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.26876787]]


데이터를 수동으로 지정할 수도 있습니다. 치수는 위 인쇄 형식과 일치하는 추가 브래킷을 사용하여 지정됩니다.

In [ ]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 Operations on Matrices
행렬을 사용하여 몇 가지 연산을 살펴보겠습니다.

<a name="toc_40015_4.4.1"></a>
### 4.4.1 Indexing


행렬에는 두 번째 인덱스가 포함됩니다. 두 개의 인덱스는 [행, 열]을 설명합니다. 액세스하면 요소 또는 행/열이 반환될 수 있습니다. 아래를 참조하세요:

In [ ]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


마지막 예에 주목할 가치가 있습니다. 행을 지정하여 행렬에 액세스하면 *1D 벡터*가 반환됩니다.

**Reshape**  
이전 예에서는 [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)를 사용하여 배열의 모양을 만들었습니다.
`a = np.arange(6).reshape(-1, 2) `
이 코드 줄은 먼저 6개 요소의 *1-D 벡터*를 생성했습니다. 그런 다음 reshape 명령을 사용하여 해당 벡터를 *2D* 배열로 재구성했습니다. 이것은 다음과 같이 작성되었을 수 있습니다.
`a = np.arange(6).reshape(3, 2)`
동일한 3행, 2열 배열에 도달합니다.
-1 인수는 배열 크기와 열 수에 따라 행 수를 계산하도록 루틴에 지시합니다.


<a name="toc_40015_4.4.2"></a>
### 4.4.2 Slicing
슬라이싱은 세 가지 값 세트(`start:stop:step`)를 사용하여 인덱스 배열을 생성합니다. 값의 하위 집합도 유효합니다. 그 사용법은 다음 예를 통해 가장 잘 설명됩니다.

In [ ]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations!
이 실습에서는 과정 1에 필요한 Python 및 NumPy 기능을 마스터했습니다.